langauge: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install: raco pkg install --deps search-auto $TRAVIS_BUILD_DIR

script:
  - raco setup --check-pkg-deps gtp-checkup

# TODO implement a "fast version" that runs in less than 50 minutes
#    PLTSTDERR="error info@gtp-checkup" racket main.rkt ${RACKET_DIR}/bin
